[package]
name = "lispox"
version = "0.1.0"
authors = ["putnamjm <putnamjm.design@gmail.edu>"]
edition = "2018"

[[bin]]
name = "lispox"
path = "src/shell/main.rs"

[lib]
name = "system"
crate-type = ["cdylib"]
bench = false
path = "src/system/lib.rs"
