[package]
name = "lispox"
version = "0.1.0"
authors = ["putnamjm <putnamjm.design@gmail.edu>"]
edition = "2018"

[[bin]]
name = "lispox"
path = "src/main.rs"

[lib]
name = "mu"
path = "src/lib.rs"

[dependencies]
memmap = "0.7.0"
nom = "5.1.2"
num = "0.2"
num-derive = "0.3"
num-traits = "0.2"